@startuml
!pragma layout smetana

component TMDB_API [
The Movie Database API
]

database Database [
Postgres Database
]

'' Styling
skinparam ArrowThickness 3
skinparam ArrowColor Orange
skinparam backgroundColor #f0f0f0
skinparam borderColor Black
skinparam borderThickness 1

skinparam class {
  BackgroundColor white
}

skinparam Component {
  BackgroundColor Lightblue
}

''

Class Application {
  +main(String[] args)
}


package "config" {
Class HibernateConfig
}

package "daos" {
Class ActorDao
Class DirectorDao
Class GenreDao
Class MovieDao
}


package "dtos" {
Class ActorDTO
Class CrewMemberDTO
Class DirectorDTO
Class GenreDTO
Class MovieDTO
Class MovieResponseDTO
}

package "entities" {
Class Actor {
+ id : Long
+ name : String
+ department : String
+ popularity : Double
+ character : String
}

Class Director {
- id : Long
- name : String
- Set<Movie> movies
}

Class Genre{
- id : Long
- name : String
- Set<Movie> movies
}

Class Movie{
- id : Long
- title : String
- originalLanguage : String
- originalTitle : String
- releaseDate : LocalDate
- popularity : Double
- voteAverage : Double
- voteCount : Integer
- Director director
- List<Genre> genres
- List<Actors> actors
}

package "exceptions" {
  class JpaException {
    +JpaException(String message)
  }
}

package "resources" {
Class Logger {
  +exceptionLog(String in)
  +consoleLog(String in)
}

package "services" {
Class ActorService
Class DirectorService
Class FetchData
Class GenreService
Class MovieService
Class SyncApiService
}

' Define relationships




@enduml@enduml